# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='ppi_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='weighted_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
