# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-15 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0002_auto_20160615_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='ppi_degree',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='weighted_degree',
        ),
    ]
