# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0003_auto_20160615_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='ppi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
