# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0004_chain_ppi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='log_abundance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='log_dN',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='log_dS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='log_evorate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
