# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-09 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0005_auto_20160907_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='log_abundance',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='log_dN',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='log_dS',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='log_evorate',
        ),
    ]
