# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0006_auto_20160909_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='abundance_unlogged',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chain',
            name='abundance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
