# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0007_auto_20160913_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='mutant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='mutant',
            field=models.BooleanField(default=False),
        ),
    ]
