# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0008_auto_20161024_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='mutant',
            field=models.BooleanField(default=False),
        ),
    ]
