# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0009_edge_mutant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='mutant',
        ),
        migrations.AlterField(
            model_name='chain',
            name='mutant',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='edge',
            name='mutant',
            field=models.IntegerField(default=0),
        ),
    ]
