# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0010_auto_20161028_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='mutant',
            field=models.IntegerField(default=0),
        ),
    ]
