# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0011_auto_20161028_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='has_mutant_data',
            field=models.BooleanField(default=False),
        ),
    ]
