# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0013_remove_chain_abundance_unlogged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='ppi',
        ),
        migrations.AddField(
            model_name='chain',
            name='other_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='uniprot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
