# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0014_auto_20161209_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
