# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0015_auto_20170622_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='ppi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
