# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteomevis', '0016_chain_ppi'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='hii',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
